# config/graphql/types/MyType.types.yaml
Company:
    type: object
    config:
        fields:
            id:
                type: "ID!"
                description: "The id of the company."
            name:
                type: "String!"
                description: "The name of the company."
            website:
                type: "String!"
                description: "The website of the company."
            country:
                type: "String!"
                description: "The country of the company."
